#pragma once
#include <map>

#define CMD_FLAG_OPTIONS { "onfire", "sneaking", "riding", "sprinting", "usingitem", "invisible", "tempted", "inlove", "saddled", "powered", "ignited", "baby", "converting", "critical", "showname", "noai", "silent", "wallclimbing", "resting", "sitting", "angry", "interested", "charged", "tamed", "orphaned", "leashed", "sheared", "gliding", "elder", "moving", "breathing", "chested", "stackable", "idling", "has_gravity", "swimming", "bribed", "layingdown", "sneezing", "trusting", "scared", "blocking", "is_illager_captain", "stunned", "roaring", "is_avoiding_mobs", "out_of_control", "playing_dead",  }

enum class ActorFlagsForCmd : int {
    ONFIRE = 1,
    SNEAKING,
    RIDING,
    SPRINTING,
    USINGITEM,
    INVISIBLE,
    TEMPTED,
    INLOVE,
    SADDLED,
    POWERED,
    IGNITED,
    BABY,
    CONVERTING,
    CRITICAL,
    SHOWNAME,
    NOAI,
    SILENT,
    WALLCLIMBING,
    RESTING,
    SITTING,
    ANGRY,
    INTERESTED,
    CHARGED,
    TAMED,
    ORPHANED,
    LEASHED,
    SHEARED,
    GLIDING,
    ELDER,
    MOVING,
    BREATHING,
    CHESTED,
    STACKABLE,
    IDLING,
    HAS_GRAVITY,
    SWIMMING,
    BRIBED,
    LAYINGDOWN,
    SNEEZING,
    TRUSTING,
    SCARED,
    BLOCKING,
    IS_ILLAGER_CAPTAIN,
    STUNNED,
    ROARING,
    IS_AVOIDING_MOBS,
    OUT_OF_CONTROL,
    PLAYING_DEAD,
};

enum class ActorFlags : int {
    ONFIRE = 0,
    SNEAKING = 1,
    RIDING = 2,
    SPRINTING = 3,
    USINGITEM = 4,
    INVISIBLE = 5,
    TEMPTED = 6,
    INLOVE = 7,
    SADDLED = 8,
    POWERED = 9,
    IGNITED = 10,
    BABY = 11,
    CONVERTING = 12,
    CRITICAL = 13,
    SHOWNAME = 14,
    NOAI = 16,
    SILENT = 17,
    WALLCLIMBING = 18,
    RESTING = 23,
    SITTING = 24,
    ANGRY = 25,
    INTERESTED = 26,
    CHARGED = 27,
    TAMED = 28,
    ORPHANED = 29,
    LEASHED = 30,
    SHEARED = 31,
    GLIDING = 32,
    ELDER = 33,
    MOVING = 34,
    BREATHING = 35,
    CHESTED = 36,
    STACKABLE = 37,
    IDLING = 41,
    HAS_GRAVITY = 48,
    SWIMMING = 56,
    BRIBED = 57,
    LAYINGDOWN = 63,
    SNEEZING = 64,
    TRUSTING = 65,
    SCARED = 67,
    BLOCKING = 71,
    IS_ILLAGER_CAPTAIN = 81,
    STUNNED = 82,
    ROARING = 83,
    IS_AVOIDING_MOBS = 85,
    OUT_OF_CONTROL = 95,
    PLAYING_DEAD = 97,
};

static std::map<ActorFlagsForCmd, ActorFlags> flagCmdMap = {
    {ActorFlagsForCmd::ONFIRE, ActorFlags::ONFIRE},
    {ActorFlagsForCmd::SNEAKING, ActorFlags::SNEAKING},
    {ActorFlagsForCmd::RIDING, ActorFlags::RIDING},
    {ActorFlagsForCmd::SPRINTING, ActorFlags::SPRINTING},
    {ActorFlagsForCmd::USINGITEM, ActorFlags::USINGITEM},
    {ActorFlagsForCmd::INVISIBLE, ActorFlags::INVISIBLE},
    {ActorFlagsForCmd::TEMPTED, ActorFlags::TEMPTED},
    {ActorFlagsForCmd::INLOVE, ActorFlags::INLOVE},
    {ActorFlagsForCmd::SADDLED, ActorFlags::SADDLED},
    {ActorFlagsForCmd::POWERED, ActorFlags::POWERED},
    {ActorFlagsForCmd::IGNITED, ActorFlags::IGNITED},
    {ActorFlagsForCmd::BABY, ActorFlags::BABY},
    {ActorFlagsForCmd::CONVERTING, ActorFlags::CONVERTING},
    {ActorFlagsForCmd::CRITICAL, ActorFlags::CRITICAL},
    {ActorFlagsForCmd::SHOWNAME, ActorFlags::SHOWNAME},
    {ActorFlagsForCmd::NOAI, ActorFlags::NOAI},
    {ActorFlagsForCmd::SILENT, ActorFlags::SILENT},
    {ActorFlagsForCmd::WALLCLIMBING, ActorFlags::WALLCLIMBING},
    {ActorFlagsForCmd::RESTING, ActorFlags::RESTING},
    {ActorFlagsForCmd::SITTING, ActorFlags::SITTING},
    {ActorFlagsForCmd::ANGRY, ActorFlags::ANGRY},
    {ActorFlagsForCmd::INTERESTED, ActorFlags::INTERESTED},
    {ActorFlagsForCmd::CHARGED, ActorFlags::CHARGED},
    {ActorFlagsForCmd::TAMED, ActorFlags::TAMED},
    {ActorFlagsForCmd::ORPHANED, ActorFlags::ORPHANED},
    {ActorFlagsForCmd::LEASHED, ActorFlags::LEASHED},
    {ActorFlagsForCmd::SHEARED, ActorFlags::SHEARED},
    {ActorFlagsForCmd::GLIDING, ActorFlags::GLIDING},
    {ActorFlagsForCmd::ELDER, ActorFlags::ELDER},
    {ActorFlagsForCmd::MOVING, ActorFlags::MOVING},
    {ActorFlagsForCmd::BREATHING, ActorFlags::BREATHING},
    {ActorFlagsForCmd::CHESTED, ActorFlags::CHESTED},
    {ActorFlagsForCmd::STACKABLE, ActorFlags::STACKABLE},
    {ActorFlagsForCmd::IDLING, ActorFlags::IDLING},
    {ActorFlagsForCmd::HAS_GRAVITY, ActorFlags::HAS_GRAVITY},
    {ActorFlagsForCmd::SWIMMING, ActorFlags::SWIMMING},
    {ActorFlagsForCmd::BRIBED, ActorFlags::BRIBED},
    {ActorFlagsForCmd::LAYINGDOWN, ActorFlags::LAYINGDOWN},
    {ActorFlagsForCmd::SNEEZING, ActorFlags::SNEEZING},
    {ActorFlagsForCmd::TRUSTING, ActorFlags::TRUSTING},
    {ActorFlagsForCmd::SCARED, ActorFlags::SCARED},
    {ActorFlagsForCmd::BLOCKING, ActorFlags::BLOCKING},
    {ActorFlagsForCmd::IS_ILLAGER_CAPTAIN, ActorFlags::IS_ILLAGER_CAPTAIN},
    {ActorFlagsForCmd::STUNNED, ActorFlags::STUNNED},
    {ActorFlagsForCmd::ROARING, ActorFlags::ROARING},
    {ActorFlagsForCmd::IS_AVOIDING_MOBS, ActorFlags::IS_AVOIDING_MOBS},
    {ActorFlagsForCmd::OUT_OF_CONTROL, ActorFlags::OUT_OF_CONTROL},
    {ActorFlagsForCmd::PLAYING_DEAD, ActorFlags::PLAYING_DEAD},
};

static std::map<ActorFlags, string> actorFlagsNameMap = {
    { ActorFlags::ONFIRE, "ONFIRE"},
    { ActorFlags::SNEAKING, "SNEAKING"},
    { ActorFlags::RIDING, "RIDING"},
    { ActorFlags::SPRINTING, "SPRINTING"},
    { ActorFlags::USINGITEM, "USINGITEM"},
    { ActorFlags::INVISIBLE, "INVISIBLE"},
    { ActorFlags::TEMPTED, "TEMPTED"},
    { ActorFlags::INLOVE, "INLOVE"},
    { ActorFlags::SADDLED, "SADDLED"},
    { ActorFlags::POWERED, "POWERED"},
    { ActorFlags::IGNITED, "IGNITED"},
    { ActorFlags::BABY, "BABY"},
    { ActorFlags::CONVERTING, "CONVERTING"},
    { ActorFlags::CRITICAL, "CRITICAL"},
    { ActorFlags::SHOWNAME, "SHOWNAME"},
    { ActorFlags::NOAI, "NOAI"},
    { ActorFlags::SILENT, "SILENT"},
    { ActorFlags::WALLCLIMBING, "WALLCLIMBING"},
    { ActorFlags::RESTING, "RESTING"},
    { ActorFlags::SITTING, "SITTING"},
    { ActorFlags::ANGRY, "ANGRY"},
    { ActorFlags::INTERESTED, "INTERESTED"},
    { ActorFlags::CHARGED, "CHARGED"},
    { ActorFlags::TAMED, "TAMED"},
    { ActorFlags::ORPHANED, "ORPHANED"},
    { ActorFlags::LEASHED, "LEASHED"},
    { ActorFlags::SHEARED, "SHEARED"},
    { ActorFlags::GLIDING, "GLIDING"},
    { ActorFlags::ELDER, "ELDER"},
    { ActorFlags::MOVING, "MOVING"},
    { ActorFlags::BREATHING, "BREATHING"},
    { ActorFlags::CHESTED, "CHESTED"},
    { ActorFlags::STACKABLE, "STACKABLE"},
    { ActorFlags::IDLING, "IDLING"},
    { ActorFlags::HAS_GRAVITY, "HAS_GRAVITY"},
    { ActorFlags::SWIMMING, "SWIMMING"},
    { ActorFlags::BRIBED, "BRIBED"},
    { ActorFlags::LAYINGDOWN, "LAYINGDOWN"},
    { ActorFlags::SNEEZING, "SNEEZING"},
    { ActorFlags::TRUSTING, "TRUSTING"},
    { ActorFlags::SCARED, "SCARED"},
    { ActorFlags::BLOCKING, "BLOCKING"},
    { ActorFlags::IS_ILLAGER_CAPTAIN, "IS_ILLAGER_CAPTAIN"},
    { ActorFlags::STUNNED, "STUNNED"},
    { ActorFlags::ROARING, "ROARING"},
    { ActorFlags::IS_AVOIDING_MOBS, "IS_AVOIDING_MOBS"},
    { ActorFlags::OUT_OF_CONTROL, "OUT_OF_CONTROL"},
    { ActorFlags::PLAYING_DEAD, "PLAYING_DEAD"},
};