#pragma once

enum class EnchantType : char {
    protection            = 0,  // max level: 3, frequency: 30, 
    fire_protection       = 1,  // max level: 3, frequency: 10, 
    feather_falling       = 2,  // max level: 0, frequency: 10, 
    blast_protection      = 3,  // max level: 3, frequency: 3,  
    projectile_protection = 4,  // max level: 3, frequency: 10, 
    thorns                = 5,  // max level: 0, frequency: 1,  
    respiration           = 6,  // max level: 0, frequency: 3,  
    depth_strider         = 7,  // max level: 4, frequency: 3,  
    aqua_affinity         = 8,  // max level: 0, frequency: 3,  
    sharpness             = 9,  // max level: 1, frequency: 30, 
    smite                 = 10, // max level: 1, frequency: 10, 
    bane_of_arthropods    = 11, // max level: 1, frequency: 10, 
    knockback             = 12, // max level: 0, frequency: 10, 
    fire_aspect           = 13, // max level: 0, frequency: 3,  
    looting               = 14, // max level: 0, frequency: 3,  
    efficiency            = 15, // max level: 0, frequency: 30, 
    silk_touch            = 16, // max level: 2, frequency: 1,  
    unbreaking            = 17, // max level: 0, frequency: 10, 
    fortune               = 18, // max level: 2, frequency: 3,  
    power                 = 19, // max level: 0, frequency: 30, 
    punch                 = 20, // max level: 0, frequency: 3,  
    flame                 = 21, // max level: 0, frequency: 3,  
    infinity              = 22, // max level: 5, frequency: 1,  
    luck_of_the_sea       = 23, // max level: 0, frequency: 3,  
    lure                  = 24, // max level: 0, frequency: 3,  
    frost_walker          = 25, // max level: 4, frequency: 3,  
    mending               = 26, // max level: 5, frequency: 3,  
    binding               = 27, // max level: 0, frequency: 1,  
    vanishing             = 28, // max level: 0, frequency: 1,  
    impaling              = 29, // max level: 0, frequency: 10, 
    riptide               = 30, // max level: 6, frequency: 3,  
    loyalty               = 31, // max level: 6, frequency: 30, 
    channeling            = 32, // max level: 0, frequency: 1,  
    multishot             = 33, // max level: 0, frequency: 3,  
    piercing              = 34, // max level: 0, frequency: 30, 
    quick_charge          = 35, // max level: 0, frequency: 10, 
    soul_speed            = 36, // max level: 0, frequency: 1,  
};

enum class ItemStackRequestActionType : char {
    Take                                     = 0,
    Place                                    = 1,
    Swap                                     = 2,
    Drop                                     = 3,
    Destroy                                  = 4,
    Consume                                  = 5,
    Create                                   = 6,
    LabTableCombine                          = 7,
    BeaconPayment                            = 8,
    MineBlock                                = 9,
    CraftRecipe                              = 10,
    CraftRecipeAuto                          = 11,
    CraftCreative                            = 12,
    CraftRecipeOptional                      = 13,
    CraftNonImplemented_DEPRECATEDASKTYLAING = 14,
    CraftResults_DEPRECATEDASKTYLAING        = 15,
};

enum class ComplexInventoryTransactionType : unsigned int {
    NormalTransaction          = 0,
    InventoryMismatch          = 1,
    ItemUseTransaction         = 2,
    ItemUseOnEntityTransaction = 3,
    ItemReleaseTransaction     = 4,
};

enum class ContainerType : char {
    NONE                   = -9,
    INVENTORY              = -1,
    CONTAINER              = 0,
    WORKBENCH              = 1,
    FURNACE                = 2,
    ENCHANTMENT            = 3,
    BREWING_STAND          = 4,
    ANVIL                  = 5,
    DISPENSER              = 6,
    DROPPER                = 7,
    HOPPER                 = 8,
    CAULDRON               = 9,
    MINECART_CHEST         = 10,
    MINECART_HOPPER        = 11,
    HORSE                  = 12,
    MINECART_COMMAND_BLOCK = 16,
    JUKEBOX                = 17,
    COMPOUND_CREATOR       = 20,
    ELEMENT_CONSTRUCTOR    = 21,
    MATERIAL_REDUCER       = 22,
    LAB_TABLE              = 23,
    BLAST_FURNACE          = 27,
    SMOKER                 = 28,
    STONECUTTER            = 29,
    HUD                    = 31,
    SMITHING_TABLE         = 33,
};

enum ActorType : int {
    item                 = 64,    // minecraft:item
    tnt                  = 65,    // minecraft:tnt
    falling_block        = 66,    // minecraft:falling_block
    moving_block         = 67,    // minecraft:moving_block
    xp_orb               = 69,    // minecraft:xp_orb
    eye_of_ender_signal  = 70,    // minecraft:eye_of_ender_signal
    ender_crystal        = 71,    // minecraft:ender_crystal
    fireworks_rocket     = 72,    // minecraft:fireworks_rocket
    fishing_hook         = 77,    // minecraft:fishing_hook
    chalkboard           = 78,    // minecraft:chalkboard
    painting             = 83,    // minecraft:painting
    leash_knot           = 88,    // minecraft:leash_knot
    boat                 = 90,    // minecraft:boat
    lightning_bolt       = 93,    // minecraft:lightning_bolt
    area_effect_cloud    = 95,    // minecraft:area_effect_cloud
    balloon              = 107,   // minecraft:balloon
    shield               = 117,   // minecraft:shield
    npc                  = 307,   // minecraft:npc
    agent                = 312,   // minecraft:agent
    armor_stand          = 317,   // minecraft:armor_stand
    tripod_camera        = 318,   // minecraft:tripod_camera
    player               = 319,   // minecraft:player
    bee                  = 378,   // minecraft:bee
    piglin               = 379,   // minecraft:piglin
    piglin_brute         = 383,   // minecraft:piglin_brute
    iron_golem           = 788,   // minecraft:iron_golem
    snow_golem           = 789,   // minecraft:snow_golem
    wandering_trader     = 886,   // minecraft:wandering_trader
    creeper              = 2849,  // minecraft:creeper
    slime                = 2853,  // minecraft:slime
    enderman             = 2854,  // minecraft:enderman
    ghast                = 2857,  // minecraft:ghast
    magma_cube           = 2858,  // minecraft:magma_cube
    blaze                = 2859,  // minecraft:blaze
    witch                = 2861,  // minecraft:witch
    guardian             = 2865,  // minecraft:guardian
    elder_guardian       = 2866,  // minecraft:elder_guardian
    ender_dragon         = 2869,  // minecraft:ender_dragon
    shulker              = 2870,  // minecraft:shulker
    vindicator           = 2873,  // minecraft:vindicator
    ravager              = 2875,  // minecraft:ravager
    evocation_illager    = 2920,  // minecraft:evocation_illager
    vex                  = 2921,  // minecraft:vex
    pillager             = 2930,  // minecraft:pillager
    elder_guardian_ghost = 2936,  // minecraft:elder_guardian_ghost
    chicken              = 4874,  // minecraft:chicken
    cow                  = 4875,  // minecraft:cow
    pig                  = 4876,  // minecraft:pig
    sheep                = 4877,  // minecraft:sheep
    mooshroom            = 4880,  // minecraft:mooshroom
    rabbit               = 4882,  // minecraft:rabbit
    polar_bear           = 4892,  // minecraft:polar_bear
    llama                = 4893,  // minecraft:llama
    turtle               = 4938,  // minecraft:turtle
    panda                = 4977,  // minecraft:panda
    fox                  = 4985,  // minecraft:fox
    hoglin               = 4988,  // minecraft:hoglin
    strider              = 4989,  // minecraft:strider
    goat                 = 4992,  // minecraft:goat
    axolotl              = 4994,  // minecraft:axolotl
    squid                = 8977,  // minecraft:squid
    dolphin              = 8991,  // minecraft:dolphin
    pufferfish           = 9068,  // minecraft:pufferfish
    salmon               = 9069,  // minecraft:salmon
    tropicalfish         = 9071,  // minecraft:tropicalfish
    cod                  = 9072,  // minecraft:cod
    glow_squid           = 9089,  // minecraft:glow_squid
    wolf                 = 21262, // minecraft:wolf
    ocelot               = 21270, // minecraft:ocelot
    parrot               = 21278, // minecraft:parrot
    cat                  = 21323, // minecraft:cat
    bat                  = 33043, // minecraft:bat
};

enum class ItemStackNetResult : char {
    Success                                          = 0,
    Error                                            = 1,
    InvalidRequestActionType                         = 2,
    ActionRequestNotAllowed                          = 3,
    ScreenHandlerEndRequestFailed                    = 4,
    ItemRequestActionHandlerCommitFailed             = 5,
    InvalidRequestCraftActionType                    = 6,
    InvalidCraftRequest                              = 7,
    InvalidCraftRequestScreen                        = 8,
    InvalidCraftResult                               = 9,
    InvalidCraftResultIndex                          = 10,
    InvalidCraftResultItem                           = 11,
    InvalidItemNetId                                 = 12,
    MissingCreatedOutputContainer                    = 13,
    FailedToSetCreatedItemOutputSlot                 = 14,
    RequestAlreadyInProgress                         = 15,
    FailedToInitSparseContainer                      = 16,
    ResultTransferFailed                             = 17,
    ExpectedItemSlotNotFullyConsumed                 = 18,
    ExpectedAnywhereItemNotFullyConsumed             = 19,
    ItemAlreadyConsumedFromSlot                      = 20,
    ConsumedTooMuchFromSlot                          = 21,
    MismatchSlotExpectedConsumedItem                 = 22,
    MismatchSlotExpectedConsumedItemNetIdVariant     = 23,
    FailedToMatchExpectedSlotConsumedItem            = 24,
    FailedToMatchExpectedAllowedAnywhereConsumedItem = 25,
    ConsumedItemOutOfAllowedSlotRange                = 26,
    ConsumedItemNotAllowed                           = 27,
    PlayerNotInCreativeMode                          = 28,
    InvalidExperimentalRecipeRequest                 = 29,
    FailedToCraftCreative                            = 30,
    FailedToGetLevelRecipe                           = 31,
    FailedToFindRecipeByNetId                        = 32,
    MismatchedCraftingSize                           = 33,
    MissingInputSparseContainer                      = 34,
    MismatchedRecipeForInputGridItems                = 35,
    EmptyCraftResults                                = 36,
    FailedToEnchant                                  = 37,
    MissingInputItem                                 = 38,
    InsufficientPlayerLevelToEnchant                 = 39,
    MissingMaterialItem                              = 40,
    MissingActor                                     = 41,
    UnknownPrimaryEffect                             = 42,
    PrimaryEffectOutOfRange                          = 43,
    PrimaryEffectUnavailable                         = 44,
    SecondaryEffectOutOfRange                        = 45,
    SecondaryEffectUnavailable                       = 46,
    DstContainerEqualToCreatedOutputContainer        = 47,
    DstContainerAndSlotEqualToSrcContainerAndSlot    = 48,
    FailedToValidateSrcSlot                          = 49,
    FailedToValidateDstSlot                          = 50,
    InvalidAdjustedAmount                            = 51,
    InvalidItemSetType                               = 52,
    InvalidTransferAmount                            = 53,
    CannotSwapItem                                   = 54,
    CannotPlaceItem                                  = 55,
    UnhandledItemSetType                             = 56,
    InvalidRemovedAmount                             = 57,
    InvalidRegion                                    = 58,
    CannotDropItem                                   = 59,
    CannotDestroyItem                                = 60,
    InvalidSourceContainer                           = 61,
    ItemNotConsumed                                  = 62,
    InvalidNumCrafts                                 = 63,
    InvalidCraftResultStackSize                      = 64,
    CannotConsumeItem                                = 66,
    ScreenStackError                                 = 67,
};

enum class ContainerEnumName : char {
    beaconPaymentItems              = 8,  //beacon_payment_items
    anvilInputItems                 = 0,  //anvil_input_items
    anvilMaterialItems              = 1,  //anvil_material_items
    anvilResultItems                = 2,  //anvil_result_items
    smithingTableInputItems         = 3,  //smithing_table_input_items
    smithingTableMaterialItems      = 4,  //smithing_table_material_items
    smithingTableResultItems        = 5,  //smithing_table_result_items
    armorItems                      = 6,  //armor_items
    containerItems                  = 7,  //container_items
    brewingInputItem                = 9,  //brewing_input_item
    brewingResultItems              = 10, //brewing_result_items
    brewingFuelItem                 = 11, //brewing_fuel_item
    combinedHotbarAndInventoryItems = 12, //combined_hotbar_and_inventory_items
    craftingInputItems              = 13, //crafting_input_items
    craftingOutputItems             = 14, //crafting_output_items
    recipeConstruction              = 15, //recipe_construction
    recipeNature                    = 16, //recipe_nature
    recipeItems                     = 17, //recipe_items
    recipeSearch                    = 18, //recipe_search
    recipeSearchBar                 = 19, //recipe_search_bar
    recipeEquipment                 = 20, //recipe_equipment
    enchantingInputItems            = 21, //enchanting_input_items
    enchantingLapisItems            = 22, //enchanting_lapis_items
    furnaceFuelItems                = 23, //furnace_fuel_items
    furnaceIngredientItems          = 24, //furnace_ingredient_items
    furnaceOutputItems              = 25, //furnace_output_items
    horseEquipItems                 = 26, //horse_equip_items
    hotbarItems                     = 27, //hotbar_items
    inventoryItems                  = 28, //inventory_items
    tradeIngredient1Items           = 30, //trade_ingredient1_items
    tradeIngredient2Items           = 31, //trade_ingredient2_items
    tradeResultItem                 = 32, //trade_result_item
    containerItems2                  = 29, //container_items
    offhandItems                    = 33, //offhand_items
    compcreateInput                 = 34, //compcreate_input
    compcreateOutput                = 35, //compcreate_output
    elemconstructOutput             = 36, //elemconstruct_output
    matreduceInput                  = 37, //matreduce_input
    matreduceOutput                 = 38, //matreduce_output
    labtableInput                   = 39, //labtable_input
    loomInputItems                  = 40, //loom_input_items
    loomDyeItems                    = 41, //loom_dye_items
    loomMaterialItems               = 42, //loom_material_items
    loomResultItems                 = 43, //loom_result_items
    furnaceIngredientItems2          = 44, //furnace_ingredient_items
    furnaceIngredientItems3          = 45, //furnace_ingredient_items
    trade2Ingredient1Item           = 46, //trade2_ingredient1_item
    trade2Ingredient2Item           = 47, //trade2_ingredient2_item
    trade2ResultItem                = 48, //trade2_result_item
    grindstoneInputItems            = 49, //grindstone_input_items
    grindstoneAdditionalItems       = 50, //grindstone_additional_items
    grindstoneResultItems           = 51, //grindstone_result_items
    stonecutterInputItems           = 52, //stonecutter_input_items
    stonecutterResultItems          = 53, //stonecutter_result_items
    cartographyInputItems           = 54, //cartography_input_items
    cartographyAdditionalItems      = 55, //cartography_additional_items
    cartographyResultItems          = 56, //cartography_result_items
    containerItems3                  = 57, //container_items
    cursorItems                     = 58, //cursor_items
    creativeOutputItems             = 59, //creative_output_items
};

enum class ContainerOffset : char {
    beaconPaymentItems         = 27, //beacon_payment_items
    anvilInputItems            = 1,  //anvil_input_items
    anvilMaterialItems         = 2,  //anvil_material_items
    smithingTableInputItems    = 51, //smithing_table_input_items
    smithingTableMaterialItems = 52, //smithing_table_material_items
    enchantingInputItems       = 14, //enchanting_input_items
    enchantingLapisItems       = 15, //enchanting_lapis_items
    tradeIngredient1Items      = 6,  //trade_ingredient1_items
    tradeIngredient2Items      = 7,  //trade_ingredient2_items
    compcreateInput            = 18, //compcreate_input
    matreduceInput             = 8,  //matreduce_input
    matreduceOutput            = 41, //matreduce_output
    loomInputItems             = 9,  //loom_input_items
    loomDyeItems               = 10, //loom_dye_items
    loomMaterialItems          = 11, //loom_material_items
    trade2Ingredient1Item      = 4,  //trade2_ingredient1_item
    trade2Ingredient2Item      = 5,  //trade2_ingredient2_item
    grindstoneInputItems       = 16, //grindstone_input_items
    grindstoneAdditionalItems  = 17, //grindstone_additional_items
    stonecutterInputItems      = 3,  //stonecutter_input_items
    cartographyInputItems      = 12, //cartography_input_items
    cartographyAdditionalItems = 13, //cartography_additional_items
    creativeOutputItems        = 50, //creative_output_items
};

enum class LegacyIDToNameMap : unsigned short {
    apple                    = 260,
    mushroom_stew            = 282,
    stone_pickaxe            = 274,
    enchanted_golden_apple   = 466,
    iron_axe                 = 258,
    golden_apple             = 322,
    pumpkin_seeds            = 361,
    bread                    = 297,
    porkchop                 = 319,
    iron_shovel              = 256,
    cooked_porkchop          = 320,
    rabbit_stew              = 413,
    sweet_berries            = 477,
    cod                      = 349,
    wooden_sword             = 268,
    golden_carrot            = 396,
    salmon                   = 460,
    wooden_shovel            = 269,
    tropical_fish            = 461,
    wooden_pickaxe           = 270,
    pufferfish               = 462,
    cooked_cod               = 350,
    wooden_axe               = 271,
    cooked_salmon            = 463,
    stone_sword              = 272,
    pumpkin_pie              = 400,
    dried_kelp               = 464,
    cookie                   = 357,
    melon_slice              = 360,
    chain                    = 758,
    beef                     = 363,
    cooked_beef              = 364,
    chicken                  = 365,
    cooked_chicken           = 366,
    netherite_axe            = 746,
    rotten_flesh             = 367,
    warped_sign              = 754,
    spider_eye               = 375,
    coal                     = 263,
    carrot                   = 391,
    diamond                  = 264,
    potato                   = 392,
    iron_ingot               = 265,
    beetroot                 = 457,
    baked_potato             = 393,
    gold_ingot               = 266,
    beetroot_seeds           = 458,
    poisonous_potato         = 394,
    iron_sword               = 267,
    beetroot_soup            = 459,
    rabbit                   = 411,
    cooked_rabbit            = 412,
    wheat_seeds              = 295,
    melon_seeds              = 362,
    nether_wart              = 372,
    iron_pickaxe             = 257,
    flint_and_steel          = 259,
    bow                      = 261,
    arrow                    = 262,
    stone_shovel             = 273,
    stone_axe                = 275,
    diamond_sword            = 276,
    diamond_shovel           = 277,
    diamond_pickaxe          = 278,
    diamond_axe              = 279,
    stick                    = 280,
    bowl                     = 281,
    netherite_ingot          = 742,
    golden_sword             = 283,
    golden_shovel            = 284,
    golden_pickaxe           = 285,
    golden_axe               = 286,
    string                   = 287,
    feather                  = 288,
    gunpowder                = 289,
    wooden_hoe               = 290,
    stone_hoe                = 291,
    iron_hoe                 = 292,
    diamond_hoe              = 293,
    golden_hoe               = 294,
    wheat                    = 296,
    leather_helmet           = 298,
    leather_chestplate       = 299,
    leather_leggings         = 300,
    leather_boots            = 301,
    chainmail_helmet         = 302,
    chainmail_chestplate     = 303,
    chainmail_leggings       = 304,
    chainmail_boots          = 305,
    iron_helmet              = 306,
    iron_chestplate          = 307,
    iron_leggings            = 308,
    iron_boots               = 309,
    diamond_helmet           = 310,
    diamond_chestplate       = 311,
    diamond_leggings         = 312,
    diamond_boots            = 313,
    golden_helmet            = 314,
    golden_chestplate        = 315,
    golden_leggings          = 316,
    golden_boots             = 317,
    chorus_fruit             = 432,
    shield                   = 513,
    flint                    = 318,
    netherite_scrap          = 752,
    painting                 = 321,
    oak_sign                 = 323,
    wooden_door              = 324,
    warped_door              = 756,
    bucket                   = 325,
    kelp                     = 335,
    water_bucket             = 326,
    lava_bucket              = 327,
    powder_snow_bucket       = 770,
    axolotl_bucket           = 517,
    minecart                 = 328,
    nether_sprouts           = 760,
    saddle                   = 329,
    iron_door                = 330,
    redstone                 = 331,
    snowball                 = 332,
    oak_boat                 = 333,
    shulker_shell            = 445,
    banner                   = 446,
    elytra                   = 444,
    medicine                 = 447,
    balloon                  = 448,
    leather                  = 334,
    brick                    = 336,
    clay_ball                = 337,
    sugar_cane               = 338,
    suspicious_stew          = 734,
    paper                    = 339,
    book                     = 340,
    slime_ball               = 341,
    chest_minecart           = 342,
    egg                      = 344,
    compass                  = 345,
    fishing_rod              = 346,
    clock                    = 347,
    glowstone_dust           = 348,
    dye                      = 351,
    bone                     = 352,
    sugar                    = 353,
    cake                     = 354,
    netherite_leggings       = 750,
    bed                      = 355,
    repeater                 = 356,
    filled_map               = 358,
    shears                   = 359,
    ender_pearl              = 368,
    honeycomb                = 736,
    blaze_rod                = 369,
    ghast_tear               = 370,
    gold_nugget              = 371,
    potion                   = 373,
    glass_bottle             = 374,
    fermented_spider_eye     = 376,
    netherite_shovel         = 744,
    blaze_powder             = 377,
    magma_cream              = 378,
    brewing_stand            = 379,
    cauldron                 = 380,
    netherite_helmet         = 748,
    ender_eye                = 381,
    glistering_melon_slice   = 382,
    spawn_egg                = 383,
    glow_ink_sac             = 518,
    raw_iron                 = 520,
    raw_gold                 = 521,
    raw_copper               = 522,
    experience_bottle        = 384,
    fire_charge              = 385,
    writable_book            = 386,
    written_book             = 387,
    emerald                  = 388,
    frame                    = 389,
    flower_pot               = 390,
    empty_map                = 395,
    skull                    = 397,
    carrot_on_a_stick        = 398,
    nether_star              = 399,
    firework_rocket          = 401,
    firework_star            = 402,
    enchanted_book           = 403,
    comparator               = 404,
    netherbrick              = 405,
    quartz                   = 406,
    tnt_minecart             = 407,
    hopper_minecart          = 408,
    hopper                   = 410,
    rabbit_foot              = 414,
    rabbit_hide              = 415,
    leather_horse_armor      = 416,
    campfire                 = 720,
    iron_horse_armor         = 417,
    golden_horse_armor       = 418,
    diamond_horse_armor      = 419,
    music_disc_13            = 500,
    music_disc_cat           = 501,
    music_disc_blocks        = 502,
    music_disc_chirp         = 503,
    music_disc_far           = 504,
    music_disc_mall          = 505,
    music_disc_mellohi       = 506,
    music_disc_stal          = 507,
    music_disc_strad         = 508,
    music_disc_ward          = 509,
    music_disc_11            = 510,
    music_disc_wait          = 511,
    trident                  = 455,
    lead                     = 420,
    name_tag                 = 421,
    glow_stick               = 422,
    mutton                   = 423,
    cooked_mutton            = 424,
    armor_stand              = 425,
    spruce_door              = 427,
    birch_door               = 428,
    jungle_door              = 429,
    acacia_door              = 430,
    dark_oak_door            = 431,
    popped_chorus_fruit      = 433,
    dragon_breath            = 437,
    splash_potion            = 438,
    lingering_potion         = 441,
    command_block_minecart   = 443,
    prismarine_shard         = 409,
    totem_of_undying         = 450,
    iron_nugget              = 452,
    nautilus_shell           = 465,
    heart_of_the_sea         = 467,
    scute                    = 468,
    turtle_helmet            = 469,
    phantom_membrane         = 470,
    crossbow                 = 471,
    spruce_sign              = 472,
    birch_sign               = 473,
    jungle_sign              = 474,
    acacia_sign              = 475,
    dark_oak_sign            = 476,
    banner_pattern           = 434,
    honey_bottle             = 737,
    camera                   = 498,
    compound                 = 499,
    ice_bomb                 = 453,
    bleach                   = 451,
    rapid_fertilizer         = 449,
    sparkler                 = 442,
    lodestone_compass        = 741,
    netherite_sword          = 743,
    netherite_pickaxe        = 745,
    netherite_hoe            = 747,
    netherite_chestplate     = 749,
    netherite_boots          = 751,
    crimson_sign             = 753,
    crimson_door             = 755,
    warped_fungus_on_a_stick = 757,
    music_disc_pigstep       = 759,
    soul_campfire            = 801,
    glow_frame               = 850,
    goat_horn                = 761,
    amethyst_shard           = 771,
    spyglass                 = 772,
    end_crystal              = 426,
};

enum class ParticleType : unsigned int {
    none                  = 0,
    bubble                = 1,
    bubblemanual          = 2,
    crit                  = 3,
    blockforcefield       = 4,
    smoke                 = 5,
    explode               = 6,
    evaporation           = 7,
    flame                 = 8,
    candleflame           = 9,
    lava                  = 10,
    largesmoke            = 11,
    reddust               = 12,
    risingborderdust      = 13,
    iconcrack             = 14,
    snowballpoof          = 15,
    largeexplode          = 16,
    hugeexplosion         = 17,
    mobflame              = 18,
    heart                 = 19,
    terrain               = 20,
    townaura              = 21,
    portal                = 22,
    watersplash           = 24,
    watersplashmanual     = 25,
    waterwake             = 26,
    dripwater             = 27,
    driplava              = 28,
    driphoney             = 29,
    stalactitedripwater   = 30,
    stalactitedriplava    = 31,
    fallingdust           = 32,
    mobspell              = 33,
    mobspellambient       = 34,
    mobspellinstantaneous = 35,
    ink                   = 36,
    slime                 = 37,
    rainsplash            = 38,
    villagerangry         = 39,
    villagerhappy         = 40,
    enchantingtable       = 41,
    trackingemitter       = 42,
    note                  = 43,
    witchspell            = 44,
    carrotboost           = 45,
    mobappearance         = 46,
    endrod                = 47,
    dragonbreath          = 48,
    spit                  = 49,
    totem                 = 50,
    food                  = 51,
    fireworksstarter      = 52,
    fireworks             = 53,
    fireworksoverlay      = 54,
    balloongas            = 55,
    coloredflame          = 56,
    sparkler              = 57,
    conduit               = 58,
    bubblecolumnup        = 59,
    bubblecolumndown      = 60,
    sneeze                = 61,
    shulkerbullet         = 62,
    bleach                = 63,
    dragondestroyblock    = 64,
    myceliumdust          = 65,
    fallingborderdust     = 66,
    campfiresmoke         = 67,
    campfiresmoketall     = 68,
    dragonbreathfire      = 69,
    dragonbreathtrail     = 70,
    soul                  = 72,
    obsidiantear          = 73,
    portalreverse         = 74,
    snowflake             = 75,
    wax                   = 80,
    electricspark         = 81,
    shriek                = 82,
};

enum class EffectType : short {
    empty           = 0,  // effect:
    speed           = 1,  // effect: potion.moveSpeed
    slowness        = 2,  // effect: potion.moveSlowdown
    haste           = 3,  // effect: potion.digSpeed
    mining_fatigue  = 4,  // effect: potion.digSlowDown
    strength        = 5,  // effect: potion.damageBoost
    instant_health  = 6,  // effect: potion.heal
    instant_damage  = 7,  // effect: potion.harm
    jump_boost      = 8,  // effect: potion.jump
    nausea          = 9,  // effect: potion.confusion
    regeneration    = 10, // effect: potion.regeneration
    resistance      = 11, // effect: potion.resistance
    fire_resistance = 12, // effect: potion.fireResistance
    water_breathing = 13, // effect: potion.waterBreathing
    invisibility    = 14, // effect: potion.invisibility
    blindness       = 15, // effect: potion.blindness
    night_vision    = 16, // effect: potion.nightVision
    hunger          = 17, // effect: potion.hunger
    weakness        = 18, // effect: potion.weakness
    poison          = 19, // effect: potion.poison
    wither          = 20, // effect: potion.wither
    health_boost    = 21, // effect: potion.healthBoost
    absorption      = 22, // effect: potion.absorption
    saturation      = 23, // effect: potion.saturation
    levitation      = 24, // effect: potion.levitation
    fatal_poison    = 25, // effect: potion.poison
    conduit_power   = 26, // effect: potion.conduitPower
    slow_falling    = 27, // effect: potion.slowFalling
    bad_omen        = 28, // effect: effect.badOmen
    village_hero    = 29, // effect: effect.villageHero
};

enum class ActorDagageCause : unsigned int {
    override = 0,
    contact = 1,
    entity_attack = 2,
    projectile = 3,
    suffocation = 4,
    fall = 5,
    fire = 6,
    fire_tick = 7,
    lava = 8,
    drowning = 9,
    block_explosion = 10,
    entity_explosion = 11,
    _void = 12,
    suicide = 13,
    magic = 14,
    wither = 15,
    starve = 16,
    anvil = 17,
    thorns = 18,
    falling_block = 19,
    piston = 20,
    fly_into_wall = 21,
    magma = 22,
    fireworks = 23,
    lightning = 24,
    charging = 25,
    temperature = 26,
    freezing = 27,
    stalactite = 28,
    stalagmite = 29,
    all = 31,
};